### ISSUE TITLE
gnome-shell now provides org.gnome.ScreenSaver.service

### ISSUE THREAD

**Issue by SolarAquarion** [getsolus/budgie-screensaver#1]

**Comment by DataDrake** [comment]
No one should be using this anymore.

**Comment by DataDrake** [comment]
Next time reference the original issue: https://github.com/solus-project/budgie-desktop/issues/2120

**Comment by SolarAquarion** [comment]
@DataDrake but even with that, the patches that were applied, there is a conflict.

**Comment by DataDrake** [comment]
I can read, thanks.

**Comment by JoshStrobl** [comment]
Re-opened as MR #2 and the related budgie-desktop PR break lock functionality, and when reverted back to the previous state, it continues to function as expected. I'll be reverting the respective commit and have more complete thoughts below.

I agree that the current situation where budgie-desktop and gnome-shell are not co-installable is not ideal. Here's a full write-up on the current situation:

- Solus uses our fork of gnome-screensaver, which merely applies some patches on top of the original codebase without any additional renames. Per the README, this was originally due to it not being developed upstream, and when we [originally proposed](https://mail.gnome.org/archives/desktop-devel-list/2016-July/msg00030.html) taking over maintainership, it was evident that there wasn't really much of a need to do so, since it was no longer part of the GNOME session experience. This has meant that up until now, us providing the `org.gnome.ScreenSaver` DBUS service file has not been problematic, as it wasn't shipped in gnome-shell in the current manner that it is now.
- The relevant gnome-settings-daemon changes around starting the screensaver service are solely related to the removal of the DO_NOT_AUTOSTART proxy flag, see [this commit](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/f7702421321ff8aeeb2aad26afefee997b63e938), so we should still be able to call out to `org.gnome.ScreenSaver` without problems.
- GNOME Shell handles proxying to `org.gnome.ScreenSaver` via its own `org.gnome.Shell.ScreenShield` interface and calls out to the ScreenSaver proxy. Not following the rest of the code because it is GJS weirdness and nothing normal like C, so not familiar with the dbus proxy wrapper functions. https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/af5aff32514d7236d3261670a5ed0c087ee3abdd

In an ideal situation, we could expose our own dbus service that proxies out to ScreenSaver as well. However the real root of this issue comes down to a situation where someone may have *both* Budgie and GNOME Shell installed at the same time. While I'm not sure how much of a problem the dbus service name stuff would be if both gnome-shell and budgie-screensaver used the same `Name=`, mostly thinking about when someone would be using `gdm` for login, we could try *just* renaming our service file itself, since [per the spec](https://www.freedesktop.org/wiki/IntroductionToDBus/) the file name is arbitrary and like with anything else, it's *what is on the inside that counts*.

I think this is all really building up to a scenario where GNOME Shell and Budgie Desktop are not co-installable. This is a situation I'm fairly comfortable with, though I recognize it may frustrate those that just want to tinker with one or the other. I don't really look at it any different than Solus' general recommendation not to intermix Plasma and other desktops, just focus on building out a single user experience and not trying to mix-and-match.

I'm open to thoughts and ideas, however I don't really have the time to fully flesh out a replacement for our gnome-screensaver fork until Budgie 11. At that point, it would likely be baked into the window manager or some other official part of budgie-desktop, and so the fork would no longer be necessary and we wouldn't be relying on `org.gnome.ScreenSaver` anyways, but rather just implementing the freedesktop screensaver bits. If someone can implement a proxy solution that allows both GNOME Shell and Budgie Desktop to co-exist, I'm happy to take a look at the patch. What I'll be doing is testing out just renaming the file and installing Budgie Desktop + GDM (instead of lightdm + slick-greeter, which is our recommendation) + GNOME Shell and see if things explode. If not, I'll keep the rename and die a bit inside.

**Comment by JoshStrobl** [comment]
> What I'll be doing is testing out just renaming the file and installing Budgie Desktop + GDM (instead of lightdm + slick-greeter, which is our recommendation) + GNOME Shell and see if things explode. If not, I'll keep the rename and die a bit inside.

Follow-up to this: Aside from the file conflict, having GDM + Budgie Desktop still works fine. Going to push the rename of the file, which I've validated still allows the appropriate dbus bits plus locking to work for Budgie. I would appreciate @gmbr3 if you'd validated this plus master of budgie-desktop where I reverted the respective change you made.

**Comment by JoshStrobl** [comment]
Closing issue as @fossfreedom has contributed a patch, which has landed, that appropriately rebrands our fork of gnome-screensaver to budgie-screensaver, and supplemental work I did in 5631e153e3cffb26cdabcec5925f9e2433ba23b3

Budgie Screensaver will see a v4.0 release early next week (likely Tuesday) alongside Budgie Desktop v10.5.3.
